---
layout: post
title: "Simulating data for cross-sectional mediation in SEM with lavaan in R"
date: 2018-11-20
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We'll need the `lavaan` package for the actual analysis and the `ggplot2` package for visualizing the effect.

```{r libraries}
library(lavaan)
library(ggplot2)
```

# Generate Data

```{r}
N <- 10000

X <- rnorm(N, 0, 1)
Med <- .7 * X  + rnorm(N, 0, 1)
Y <- .3 * X + .3 * Med + rnorm(N, 0, 1)
dat <- cbind.data.frame(X, Med, Y)

```

We then create our observed variables with loadings of .8 and residual errors of ~ .36. The observed variables will thus have a total variance of ~ 1.0.

```{r}

dat$x1 <- .8 * X +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$x2 <- .8 * X +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$x3 <- .8 * X +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$m1 <- .8 * Med + (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$m2 <- .8 * Med + (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$m3 <- .8 * Med + (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$y1 <- .8 * Y +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$y2 <- .8 * Y +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))
dat$y3 <- .8 * Y +   (sqrt(1 - .8^2) * rnorm(N, 0, 1))

model <- '

            X =~ x1 + x2 + x3
            Med =~ m1 + m2 + m3
            Y =~ y1 + y2 + y3

            Med ~ a*X
            Y ~ c*X
            Y ~ b*Med

            ab := a*b

            abc := ab + c
          
'


mod <- sem(model = model, data = dat, std.lv = T)

summary(mod, fit.measures = T)

```
